### ISSUE TITLE
Add more code examples

### ISSUE THREAD

**Issue by rask** [OxideMod/Oxide.Docs#27]
Currently some JS, Lua and Python examples are missing (e.g. console and chat commands).

Additionally some documentation on how to use the data table system with JavaScript properly would be nice. Meaning what kind of data structures and handling are supported.

Current documentation simply loads the data table, sets a string key to `true` and then saves the data table.

**Comment by Rask** [comment]
Created PR28 for chat and console commands issue. https://github.com/OxideMod/Docs/pull/28

**Comment by lukespragg** [comment]
Looking good so far. :)
